source/user_guide/feature_importance.rst
source/user_guide/regression.rst
source/user_guide/reinforcement_learning.rst
source/user_guide/save_load.rst
source/user_guide/time_series.rst

Update RL docs to link to RL recipes and other minor formatting.
Includes
- Time series updates
- Another intro sentence for feature importance
- A few more miscellaneous fixes

Update RL docs

---

source/user_guide/installing.rst

- Updated pip package name
- Updated function names
- Updated product names

17392 update installation instructions for howso engine

---

source/user_guide/feature_attributes.md
source/user_guide/terminology.rst

Removed all mention of Diveplane from docs no one is currently working on (terminology, feature_attributes).

17410 Removing all mention of Diveplane

---

source/index.rst

Updated to match GitHub intro summary and links to install and a few intro user guides.

Updated Homepage to Howso Branding

---

source/user_guide/concepts.rst

DRAFT of the Concepts page, following the outline I found [here](https://diveplane.visualstudio.com/dp/_wiki/wikis/dp.wiki/758/Howso-Engine-Documentation-Sitemap). These still need editing, but would like others' thoughts as I go forward to make sure I'm on the right track.

#17400 concepts docs

---

source/user_guide/index.rst
source/user_guide/json_features.rst

- Adds a user guide for JSON/YAML features.

17304: Add user guide for JSON features

---

source/user_guide/index.rst

- Remove JSON as a feature guide from user guides index

17441: Remove JSON as a feature guide from user guides index

---

source/getting_started/index.rst
source/index.rst
source/user_guide/index.rst

remove links to regression and replace with links to predictions

17443 Fix links to regression

---

source/user_guide/anomaly_detection.rst
source/user_guide/derived_features.rst
source/user_guide/editing_case_weighting.rst
source/user_guide/feature_importance.rst
source/user_guide/generative_AI_synth.rst
source/user_guide/model_performance.rst
source/user_guide/reinforcement_learning.rst
source/user_guide/save_load.rst

- Corrected titles of Prerequisites section to be consistent with other pages.
- Removed code snippet captions on various pages to match others.

17452 miscellaneous polishing

---

source/user_guide/predictions.rst
source/user_guide/save_load.rst

add api links

---

LICENSE.txt

Update to OSS license - AGPLv3

17446: Update to OSS license - AGPLv3, MAJOR

---

source/user_guide/basic_workflow.rst
source/user_guide/generative_AI_synth.rst
source/user_guide/reinforcement_learning.rst
source/user_guide/save_load.rst

Fixing typos found throughout the docs.

fixed typos seen when looking around the user guide site

---

source/_static/css/theme.css
source/_templates/layout.html

- Adds Inter font family
- Corrects additional favicon link paths
- Includes fathom analytics

17514: Add font family and include fathom

---

source/user_guide/save_load.rst

Simply adds a line describing the default behavior.

Makes the default behavior clear

---

source/getting_started/client_configuration.rst

Makes some changes to the previous PR to address some after-merge comments.

17829: Tweaks the configuration docs

---

source/getting_started/terminology.rst
source/index.rst
source/user_guide/basic_tools.rst
source/user_guide/capabilities.rst
source/user_guide/datasets.rst
source/user_guide/generative_AI_synth.rst
source/user_guide/index.rst
source/user_guide/influential_data_counterfactuals_uncertainty.rst
source/user_guide/understandability_tools.rst

Pull request to clean up the user guides intro pages and consistency.

17836 ug intro

---

source/getting_started/installing.rst
source/getting_started/intro.rst
source/index.rst

PR to fix minor edits and typos.

17848-edits

---

source/examples/index.rst
source/getting_started/dev_container.rst
source/getting_started/installing.rst

Updated 'Getting Started/Installation' with links and info about using Howso Dev Containers

17910: Updated 'Getting Started/Installation' with links and info about using Howso Dev Containers

---

source/conf.py

Increase navigation depth in sidebar to show class methods

18502: Increase navigation depth in sidebar to show class methods

---

source/getting_started/client_configuration.rst

This PR fixes some indentation that created confusion for new users.

18587: Fix indentation

---

source/user_guide/time_series.rst

In light of the new continue_series_features/values parameters of react_series, I update the time series user guide to reflect the new capabilities of react_series.

18531: Adds a section about forecasting to the time-series user guide

---

source/examples/index.rst
source/getting_started/terminology.rst
source/user_guide/advanced_capabilities/editing_case_weighting.rst
source/user_guide/advanced_capabilities/feature_importance.rst
source/user_guide/advanced_capabilities/time_series.rst
source/user_guide/basic_capabilities/basic_workflow.rst

Recipes repo has been reorged. This PR is to update the docs to reflect the new changes

20272: Updates docs to link new recipes

---

source/conf.py

Forces automatic typehint documentation, ignoring the typehints that were written by users.

10471: Forces automatic typehint documentation

---

source/getting_started/terminology.rst

21116: Update terminology.rst

---

source/getting_started/concepts.rst
source/getting_started/intro.rst
source/getting_started/terminology.rst
source/user_guide/advanced_capabilities/case_importance.rst
source/user_guide/advanced_capabilities/feature_importance.rst
source/user_guide/basic_capabilities/conviction.rst
source/user_guide/basic_capabilities/residuals.rst
source/user_guide/concepts/global_vs_local.rst

Refactored all mentions of renamed functions from [FeatureInfluenceRenames.xls](https://diveplane-my.sharepoint.com/:x:/g/personal/cmack_howso_com/EV9BqmEDGolAhoqPkKLIld0BMIyVFwH8EDo2pt8-78XqHw?e=rroB5A)

22931: Feature Influence Rename
